// Portfolio data — Eissa Islam
window.PortfolioData = {
  identity: {
    name: 'Eissa Islam',
    role: 'AI Engineer',
    location: 'Giza, Egypt',
    email: 'eissaislam.buss@gmail.com',
    phone: '+20 112 990 7116',
    github: 'https://github.com/eissa2002',
    linkedin: 'https://www.linkedin.com/in/eissa-islam-775291200/',
    cv: 'assets/Eissa_Islam_CV.pdf',
    summary: 'AI Engineer with 2+ years building production AI systems: LLM agents, RAG, voice AI, and the backends behind them. I ship end to end, from architecture to deployment, for a university, a law firm in Cairo and Dubai, and my own live SaaS. Published IEEE author (ITC-Egypt 2024).',
    headline: 'Production AI systems. End-to-end delivery.',
  },

  kpis: [
    { label: 'Years XP',      value: '2+',   sub: 'production AI shipping' },
    { label: 'Tests written', value: '560+', sub: 'JobPilot + WhatsApp agent' },
    { label: 'Leads shipped', value: '158K', sub: 'deduplicated, for a client' },
    { label: 'IEEE pubs',     value: '1',    sub: 'ITC-Egypt 2024' },
  ],

  // Featured projects (top 3)
  featured: [
    {
      id: 'PRJ-001',
      slug: 'jobpilot',
      name: 'JobPilot AI',
      tagline: 'Multi-tenant job search SaaS',
      status: 'in-use',
      statusLabel: 'Live · Open signup',
      desc: 'Live SaaS with ~20 real users. Pulls jobs from 12 sources, dedupes them, and scores each with a hybrid engine: rules, keyword coverage, and LLM fit. Tailors a CV and cover letter per job. An LLM router with circuit breaker and quota accounting spans 4 providers and 7 models. 412 tests, $0/month infrastructure.',
      stack: ['Python', 'FastAPI', 'Next.js', 'SQLAlchemy 2.0', 'PostgreSQL', 'Supabase', 'Playwright', 'Telegram'],
      tags: ['Agents', 'LLM', 'Backend'],
      viz: 'pipeline',
    },
    {
      id: 'PRJ-002',
      slug: 'legal-ai-suite',
      name: 'Legal Operations AI Platform',
      tagline: 'Three production AI agents for a law firm',
      status: 'in-use',
      statusLabel: 'Client · Cairo & Dubai',
      desc: 'B2B Lead Intelligence: 158K deduplicated B2B leads, 92% reachable by phone, delivered. Client Intake Automation on the official WhatsApp Cloud API: exactly-once replies enforced by a Postgres partial unique index, HMAC-SHA256 PII redaction, append-only audit log, 155 tests. Arabic Legal Document Intelligence: case files to structured reports, with bidi-aware PDF extraction (MVP demoed live).',
      stack: ['FastAPI', 'PostgreSQL', 'Alembic', 'Redis / arq', 'WhatsApp Cloud API', 'Chatwoot', 'Docker Compose', 'Gemini', 'Groq'],
      tags: ['Agents', 'LLM', 'Backend'],
      viz: 'suite',
    },
    {
      id: 'PRJ-003',
      slug: 'robomust',
      name: 'RoboMUST',
      tagline: 'Voice-enabled AI learning platform',
      status: 'in-use',
      statusLabel: 'Live · MUST',
      desc: 'In production at the university. Students ask in Arabic or English, by voice or text. Answers come from the professor\'s own course files, with the source attached. BGE-M3 puts both languages in one vector space. Whisper large-v3 in, Edge-TTS out, Groq Llama 3.3 70B with Ollama fallback. 14 routers, 3 roles.',
      stack: ['FastAPI', 'ChromaDB', 'BGE-M3', 'Groq', 'Ollama', 'Whisper', 'Edge-TTS', 'Docling'],
      tags: ['RAG', 'LLM', 'Voice'],
      viz: 'wave',
    },
  ],

  // Full project log
  projects: [
    { id: 'PRJ-001', name: 'JobPilot AI',            year: 2025, role: 'Solo build', tags: ['Agents','LLM','Backend'],  stack: 'FastAPI · Next.js · PostgreSQL · 4 LLM providers', status: 'in-use' },
    { id: 'PRJ-002', name: 'Client Intake Automation (WhatsApp)',  year: 2026, role: 'Contract',   tags: ['Agents','Backend'],        stack: 'FastAPI · PostgreSQL · arq · Meta Cloud API',     status: 'dev' },
    { id: 'PRJ-003', name: 'B2B Lead Intelligence Pipeline', year: 2026, role: 'Contract',   tags: ['Data','Scraping'],         stack: 'Python · SQLite · union-find dedupe',             status: 'in-use' },
    { id: 'PRJ-004', name: 'Arabic Legal Document Intelligence', year: 2026, role: 'Contract',   tags: ['LLM','NLP','Arabic'],      stack: 'FastAPI · Gemini · Groq · Arabic PDF',            status: 'dev' },
    { id: 'PRJ-005', name: 'Bilingual Realtime Voice Sales Agent', year: 2026, role: 'Contract',   tags: ['Voice','LLM','Agents'],    stack: 'OpenAI Realtime · Asterisk · FastAPI',            status: 'dev' },
    { id: 'PRJ-006', name: 'RoboMUST',               year: 2025, role: 'Solo build', tags: ['RAG','LLM','Voice'],       stack: 'FastAPI · ChromaDB · BGE-M3 · Whisper',           status: 'in-use' },
    { id: 'PRJ-007', name: 'Enterprise Brain',       year: 2025, role: 'Architect',  tags: ['RAG','Agents','LLM'],      stack: 'LangGraph · BGE-m3 · Qdrant · Next.js',           status: 'online' },
    { id: 'PRJ-008', name: 'ShopIntel',              year: 2025, role: 'Lead',       tags: ['LLM','NLP','Scraping'],    stack: 'FastAPI · Selenium · MongoDB · LLMs',             status: 'in-use' },
    { id: 'PRJ-009', name: 'Face Recognition Attendance System', year: 2025, role: 'Contributor',tags: ['CV','Production'],         stack: 'dlib · face_recognition · FastAPI',               status: 'in-use' },
    { id: 'PRJ-010', name: 'Waste Sorting Vision System', year: 2025, role: 'Solo build', tags: ['CV','Edge'],               stack: 'YOLOv8 · OpenCV · Edge deploy',                   status: 'in-use' },
    { id: 'PRJ-011', name: 'Quranic Tafsir RAG Assistant', year: 2024, role: 'Solo build', tags: ['RAG','LLM'],               stack: 'ChromaDB · MongoDB · LangChain · HF',             status: 'online' },
    { id: 'PRJ-012', name: 'Web-Grounded RAG Chat Platform', year: 2024, role: 'Engineer',   tags: ['RAG','LLM','Scraping'],    stack: 'MongoDB · ChromaDB · RAG',                        status: 'online' },
    { id: 'PRJ-013', name: 'ScrapeMaster: Dataset Collection Tool', year: 2024, role: 'Solo build', tags: ['Scraping','Tools'],        stack: 'Tkinter · Selenium · BS4',                        status: 'online' },
    { id: 'PRJ-014', name: 'Fraud Detection & Credit Scoring', year: 2024, role: 'Trainee',    tags: ['ML','Finance'],            stack: 'SMOTE · Ensemble · Scikit-learn',                 status: 'idle' },
    { id: 'PRJ-015', name: 'Applied MLOps Pipelines (4 projects)', year: 2024, role: 'Intern',     tags: ['MLOps','ML'],              stack: 'MLflow · HuggingFace · Azure AI',                 status: 'idle' },
    { id: 'PRJ-016', name: 'Parkinsonian Gait Severity Assessment', year: 2024, role: 'Lead',       tags: ['CV','Research','IEEE'],    stack: 'Mediapipe · Keras · Scikit-learn',                status: 'online' },
    { id: 'PRJ-017', name: 'Prostate Cancer Detection (Deep Learning)', year: 2023, role: 'Solo build', tags: ['CV','Medical'],            stack: 'TensorFlow · Keras · DICOM',                      status: 'idle' },
  ],

  experience: [
    {
      from: '2026-07', to: 'Present', current: true,
      role: 'AI Engineer (Contract)',
      org: 'Law firm · Cairo & Dubai',
      loc: 'Remote',
      bullets: [
        'Delivered a B2B lead intelligence pipeline: 158K deduplicated B2B leads, 92% reachable by phone, with a schema that stops two reps getting the same firm.',
        'Building a WhatsApp client intake automation on the official Cloud API: exactly-once replies, PII redaction, audit log, 155 tests.',
        'Built an Arabic legal document intelligence MVP that turns case files into structured reports; demoed live to the client.',
        'Building a bilingual (Arabic/English) realtime voice sales agent on OpenAI Realtime with a custom Asterisk telephony lab.',
      ],
    },
    {
      from: '2025-02', to: 'Present', current: true,
      role: 'AI Engineer',
      org: 'Misr University for Science & Technology',
      loc: 'Giza, Egypt',
      bullets: [
        'Spearheading university-wide smart infrastructure — 3 production AI systems in active campus use.',
        'Built RoboMUST, a voice-enabled AI learning platform in production: cross-lingual RAG over course files, quiz generation, summarization.',
        'Developed ShopIntel — LLM shopping assistant with multi-platform scraping and personalized planning.',
        'Deployed campus-wide facial recognition attendance covering multiple departments.',
        'Built YOLOv8 garbage classification system deployed at physical sorting stations.',
      ],
    },
    {
      from: '2024-10', to: '2024-12',
      role: 'AI Engineer',
      org: 'AiTech',
      loc: 'Egypt',
      bullets: [
        'Architected an intelligent chat system using web scraping + MongoDB + ChromaDB + RAG.',
        'Built a Quranic RAG chatbot grounded in classical tafsir with a dual-vector pipeline.',
        'Developed ScrapeMaster — a Tkinter desktop tool for YouTube/web image dataset collection.',
      ],
    },
    {
      from: '2024-04', to: '2024-10',
      role: 'ML Engineer Intern',
      org: 'Digital Egypt Initiative (MCIT)',
      loc: 'Egypt',
      bullets: [
        'Hands-on MLOps with MLflow, Hugging Face, and Azure AI across 4 applied projects.',
        'Built end-to-end data pipelines and deployment workflows shipping evaluated ML models.',
      ],
    },
    {
      from: '2024-06', to: '2024-08',
      role: 'Data Scientist Trainee',
      org: 'Banque Misr — Rowad Internship',
      loc: 'Egypt',
      bullets: [
        'Designed fraud detection and credit scoring models on imbalanced data using SMOTE + ensembles.',
        'Delivered feature engineering reports in an Agile environment with analysts and data engineers.',
      ],
    },
    {
      from: '2023-05', to: '2024-08',
      role: 'Data Science Trainee',
      org: 'ALX Africa & ExploreAI',
      loc: 'Remote',
      bullets: [
        'Capstone projects in model training, evaluation, and dashboards on real-world datasets.',
        'Applied supervised + unsupervised methods across structured and unstructured data.',
      ],
    },
    {
      from: '2023-01', to: '2023-07',
      role: 'ML Intern',
      org: 'MUST AI Tech R&D Center',
      loc: 'Giza, Egypt',
      bullets: [
        'Built a deep learning prostate cancer detection model in TensorFlow/Keras.',
        'Led DICOM preprocessing through final performance validation end-to-end.',
      ],
    },
  ],

  education: {
    degree: 'B.Sc. Information Technology — Major: AI',
    org: 'Misr University for Science and Technology',
    loc: 'Giza, Egypt',
    span: 'Sept 2019 — Jun 2024',
    gpa: '3.41 / 4.0',
  },

  stack: [
    { group: 'LLM & Agents',      items: ['LangChain', 'LangGraph', 'OpenAI Realtime', 'Gemini API', 'Groq / Llama 3', 'Ollama', 'LLM routing & fallback', 'Prompt Eng'] },
    { group: 'RAG & Vector DBs',  items: ['BGE-m3', 'Re-ranking', 'Semantic Search', 'ChromaDB', 'Qdrant', 'Milvus', 'PGVector', 'Docling'] },
    { group: 'Voice & Messaging', items: ['Whisper', 'Edge-TTS', 'Asterisk', 'WhatsApp Cloud API', 'Chatwoot', 'Telegram Bot API'] },
    { group: 'Backend & APIs',    items: ['FastAPI', 'SQLAlchemy 2.0 async', 'asyncpg', 'Alembic', 'Redis / arq', 'Celery', 'REST', 'SSE'] },
    { group: 'Languages & DBs',   items: ['Python', 'TypeScript', 'SQL', 'PostgreSQL', 'Supabase', 'MongoDB', 'SQLite'] },
    { group: 'Frontend',          items: ['Next.js', 'React', 'Browser extensions (MV3)', 'Streamlit'] },
    { group: 'MLOps & Cloud',     items: ['Docker Compose', 'GitHub Actions', 'MLflow', 'Azure AI', 'AWS', 'Oracle Cloud (ARM)', 'Sentry', 'systemd'] },
    { group: 'ML / DL & CV',      items: ['PyTorch', 'TensorFlow', 'Scikit-learn', 'HF Transformers', 'YOLOv8', 'OpenCV', 'Mediapipe'] },
    { group: 'Scraping & Auto',   items: ['Playwright', 'Scrapling', 'Selenium', 'BeautifulSoup', 'httpx', 'n8n', 'APScheduler'] },
  ],

  publication: {
    year: '2024',
    venue: 'IEEE ITC-Egypt 2024',
    title: 'Parkinsonian Gait Severity in Older Adults with Dementia Using Natural Gait Video Analysis',
    desc: 'Vision-based gait analysis system for dementia patients reaching 92% validation accuracy via 2D/3D video data and a multi-model ML ensemble.',
    url: 'https://ieeexplore.ieee.org/document/10620575',
  },
};
